version: '3'
services:
#mssql docker
  ekino-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - ekinonet

  ekino-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eKino=Server=ekino-sql,1433;Database=170102;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5000:5050
    networks:
      - ekinonet      
    links:
      - ekino-sql
    depends_on:
      - ekino-sql
      
networks:
  ekinonet:
    driver: bridge      